### ISSUE TITLE
Fix Please 

### ISSUE THREAD

**Issue by LeePC** [miclol/WirelessNBS#1]
{
  "instruments": {
	"Piano": [[341, 5, 326], [341, 5, 325], [341, 5, 324], [341, 5, 323], [341, 5, 322], [341, 5, 321]],
	"Double bass": [[341, 5, 320], [341, 5, 319], [341, 5, 318]],
	"Flute": [[341, 5, 317]],
	"Pling": [[341, 5, 316], [341, 5, 315], [341, 5, 314]],
	"Bass drum": [[341, 5, 313], [341, 5, 312], [341, 5, 311]],
	"Snare drum": [[341, 5, 310], [341, 5, 309]],
	"Click": [[341, 5, 308], [341, 5, 307]]
  },
  "obstructions": [[341, 5, 327], [341, 5, 306]]
}
![2021-09-19_14 05 20](https://user-images.githubusercontent.com/8704225/133916105-861278d0-b8da-4ce1-912f-fe7fd7b21091.png)

It's not working.

**Comment by miclol** [comment]
So since you closed the issue... did you figure out the problem?

**Comment by LeePC** [comment]
Yes, I checked what the problem was.
It's working properly.
