### ISSUE TITLE
I don't think there's any problem. Then, what's the problem?

### ISSUE THREAD

**Issue by LeePC** [miclol/WirelessNBS#2]
[1.zip](https://github.com/miclol/WirelessNBS/files/7214775/1.zip)
I tried to test it, but it didn't work.
![Screenshot_2](https://user-images.githubusercontent.com/8704225/134447898-09185bc0-03ab-4dcc-984c-40b7082f008b.png)

**Comment by LeePC** [comment]
![2021-09-23_11 49 33](https://user-images.githubusercontent.com/8704225/134448072-7f87f983-fdea-498f-9c64-6972bd0e66ef.png)

**Comment by miclol** [comment]
`-----------------------------------v--`
`"guitar": [[10, 5, 246], [10, 5, 246]],`
`--------------------------------------`
Did you mean to write: [10, 5, 247]?

**Comment by LeePC** [comment]
ah.....sorry....
