### ISSUE TITLE
notebetter mods support please

### ISSUE THREAD

**Issue by LeePC** [miclol/WirelessNBS#3]
[https://www.youtube.com/watch?v=VVs4wXbXPFw](url)

notebetter 1.16.5 version
Can't we apply with this?
custom noteblock addon mods

https://github.com/Gorayan/NoteBetter
and notebetter mods 1.16.5 fabric

**Comment by miclol** [comment]
Unfortunately, I can't run the mod in 1.16.5 for some reason so I don't know how to help with this... Sorry!
