### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by Hightechnyangtoml** [miclol/WirelessNBS#4]
![image](https://github.com/miclol/WirelessNBS/assets/90317243/f52912bc-fe2f-458b-95b9-be157afa7ca5)
![image](https://github.com/miclol/WirelessNBS/assets/90317243/1bd19cb9-43d9-4daf-bff1-efafad24949f)

{
"instruments": {
"Piano": [[1, 20, 38]],
"Click": [[1, 20, 39]],
"Bass Drum": [[1, 20, 40]],
"Double Bass": [[1, 20, 41], [1, 20, 42]],
"Guitar": [[1, 20, 43]],
"Bell": [[1, 20, 44]],
"Pling": [[1, 20, 45]],
"Chime": [[1, 20, 47], [1, 20, 48], [1, 20, 49], [1, 20, 54],
"Flute": [[1, 20, 50], [1, 20, 51], [1, 20, 55]],
"Iron Xylophone": [[1, 20, 52], [1, 20, 53]],
},
"obstructions": [[1, 20, 37], [1, 20, 56]]
}

**Comment by miclol** [comment]
I think you are missing a guitar noteblock in the configuration. In the image, I see 2 but in the configuration, you only have 1.

**Comment by Hightechnyangtoml** [comment]
o i fixed ty
